### PR TITLE
Add accelerated-arrays

### PR DESCRIPTION
**Pull request by oseiskar**

### CODE REVIEW

**Comment by Bercon** [comment]
CI fails on opengl. Mac build also fails on it, but a bit differently:
```
In file included from /Users/jerry/git/odometry/mobile-cv-suite/accelerated-arrays/src/opengl/adapters.cpp:4:
/Users/jerry/git/odometry/mobile-cv-suite/accelerated-arrays/src/opengl/adapters.hpp:7:10: fatal error: 'GLES3/gl3.h' file not found
#include <GLES3/gl3.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/accelerated-arrays.dir/src/opengl/adapters.cpp.o] Error 1
```

I can try to debug the Mac build tomorrow

**Comment by oseiskar** [comment]
@Bercon Thanks, that would be great! On the Mac, you could try building without [this flag](https://github.com/AaltoML/mobile-cv-suite/pull/20/files#diff-0b53839fadf2283c800bd560ca678940c0877eb3efe332ae26ae341922b1eeddR11) (`-DWITH_OPENGL_ES=ON`). It works on my machine both with an without it but you need to have OpenGL ES development libraries installed (not always the case even if "normal" OpenGL works)

**Comment by oseiskar** [comment]
I'm also debugging the Ubuntu CI machine GL problem here first https://github.com/AaltoML/accelerated-arrays/pull/1 (a lot faster that way)

**Comment by oseiskar** [comment]
Probably good to check the Mac build before merging

**Pull request merged**
