### PR TITLE
Fix cereal build for the packaged version

### PR DESCRIPTION
**Pull request by oseiskar**

### CODE REVIEW

**Review by pekkaran — APPROVED** [review]
Looks good. Tested the host build to work.

**Comment by oseiskar** [comment]
I'm still testing on my machine, the first version before the force push did not work... Quite slow to build locally :)

**Comment by pekkaran** [comment]
> I'm still testing on my machine, the first version before the force push did not work... Quite slow to build locally :)

I got the force pushed commit and just ran `scripts/build.sh cereal`.

**Comment by Bercon** [comment]
On my Mac something seems broken, I'll have a look tomorrow:

```
++ git submodule update /Users/jerry/git/odometry/mobile-cv-suite/suitesparse
Submodule path 'suitesparse': checked out '51d622f64afaa8cee65116fa60f76241c3249baf'
+++ realpath /Users/jerry/git/odometry/mobile-cv-suite/build/licenses
/Users/jerry/git/odometry/mobile-cv-suite/scripts/components/suitesparse.sh: line 11: realpath: command not found
++ ABS_LICENSE_DIR=
```

**Comment by oseiskar** [comment]
@Bercon I suspect that is easiest fixed by running `brew install coreutils` on your machine (cf. https://github.com/whatwg/html-build/issues/90) ... or finding a more cross-platform workaround for the `realpath` command (broken in this commit https://github.com/AaltoML/mobile-cv-suite/commit/34dcf6b4400aface065674390485abc8cef00332)

**Comment by Bercon** [comment]
After installing coreutils, it works 👍

**Pull request merged**
